In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/1900_2021_disasters.csv")

In [3]:
important_cols = [
    'Year',
    'Disaster Type',
    'Country',
    'Region',
    'Continent',
    'Total Deaths',
    'No Injured',
    'No Affected',
    'Total Affected',
    "Total Damages ('000 US$)"
]

df = df[important_cols]

In [4]:
df.rename(columns={
    'Disaster Type':'Disaster_Type',
    'Total Deaths':'Deaths',
    'No Injured':'Injured',
    'No Affected':'Affected',
    'Total Affected':'Total_Affected',
    "Total Damages ('000 US$)":"Total_Damages_USD"
}, inplace=True)

In [5]:
df.isnull().sum()

Year                     0
Disaster_Type            0
Country                  0
Region                   0
Continent                0
Deaths                4445
Injured              10993
Affected              5798
Total_Affected        3603
Total_Damages_USD     9781
dtype: int64

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               14644 non-null  int64
 1   Disaster_Type      14644 non-null  str
 2   Country            14644 non-null  str
 3   Region             14644 non-null  str
 4   Continent          14644 non-null  str
 5   Deaths             10199 non-null  float64
 6   Injured            3651 non-null   float64
 7   Affected           8846 non-null   float64
 8   Total_Affected     11041 non-null  float64
 9   Total_Damages_USD  4863 non-null   float64
dtypes: float64(5), int64(1), str(4)
memory usage: 1.7 MB

In [7]:
df.duplicated().sum()

np.int64(189)

In [8]:
df.isnull().sum()

Year                     0
Disaster_Type            0
Country                  0
Region                   0
Continent                0
Deaths                4445
Injured              10993
Affected              5798
Total_Affected        3603
Total_Damages_USD     9781
dtype: int64

In [9]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (14644, 10)
After: (14455, 10)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
cols = [
    'Deaths',
    'Injured',
    'Affected',
    'Total_Affected',
    'Total_Damages_USD'
]

df[cols] = df[cols].fillna(0)

In [12]:
df.isnull().sum()

Year                 0
Disaster_Type        0
Country              0
Region               0
Continent            0
Deaths               0
Injured              0
Affected             0
Total_Affected       0
Total_Damages_USD    0
dtype: int64

In [13]:
num_cols = [
    'Deaths',
    'Injured',
    'Affected',
    'Total_Affected',
    'Total_Damages_USD'
]

df[num_cols] = df[num_cols].astype(int)

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 14455 entries, 0 to 14643
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               14455 non-null  int64
 1   Disaster_Type      14455 non-null  str
 2   Country            14455 non-null  str
 3   Region             14455 non-null  str
 4   Continent          14455 non-null  str
 5   Deaths             14455 non-null  int64
 6   Injured            14455 non-null  int64
 7   Affected           14455 non-null  int64
 8   Total_Affected     14455 non-null  int64
 9   Total_Damages_USD  14455 non-null  int64
dtypes: int64(6), str(4)
memory usage: 1.8 MB

In [15]:
df['Decade'] = (df['Year']//10)*10

In [16]:
def severity(deaths):
    if deaths >= 1000:
        return "High"
    elif deaths >= 100:
        return "Medium"
    else:
        return "Low"

df['Severity'] = df['Deaths'].apply(severity)

In [17]:
df[['Deaths','Severity']].head()

   Deaths Severity
0      36      Low
1      13      Low
2       0      Low
3  300000     High
4      17      Low

In [18]:
df.head()

,Year,Disaster_Type,Country,Region,Continent,Deaths,Injured,Affected,Total_Affected,Total_Damages_USD,Decade,Severity
0,1970,Flood,Argentina,South America,Americas,36,0,0,0,25000,1970,Low
1,1970,Storm,Australia,Australia and New Zealand,Oceania,13,0,0,0,72475,1970,Low
2,1970,Flood,Benin,Western Africa,Africa,0,0,0,0,200,1970,Low
3,1970,Storm,Bangladesh,Southern Asia,Asia,300000,0,3648000,3648000,86400,1970,High
4,1970,Storm,Bangladesh,Southern Asia,Asia,17,0,110,110,0,1970,Low

In [20]:
import os

print(os.path.exists("../data/processed"))

True

In [23]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [24]:
df.to_csv("../data/processed/disaster_cleaned.csv", index=False)