In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/raw/1900_2021_disasters.csv")

In [8]:
df.head()

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1970-0013-ARG,1970,13,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,25000.0,15.001282,NaN,NaN,NaN,NaN
1,1970-0109-AUS,1970,109,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,Ada,...,NaN,NaN,NaN,NaN,72475.0,15.001282,NaN,NaN,NaN,NaN
2,1970-0044-BEN,1970,44,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,200.0,15.001282,NaN,NaN,NaN,NaN
3,1970-0063-BGD,1970,63,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,...,NaN,3648000.0,NaN,NaN,86400.0,15.001282,NaN,NaN,NaN,NaN
4,1970-0026-BGD,1970,26,NaN,Natural,Meteorological,Storm,NaN,NaN,NaN,...,NaN,110.0,NaN,NaN,NaN,15.001282,NaN,NaN,NaN,NaN

In [9]:
df.tail()

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
14639,2021-0449-YEM,2021,449,FL-2021-000110,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,67980.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14640,2021-0075-ZAF,2021,75,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,400.0,NaN,NaN,75000.0,NaN,1;2,2707;77311;77312;77313;77315,77364;77367,"Free State, KwaZulu-Natal, Limpopo, Mpumalanga..."
14641,2021-0599-COD,2021,599,EP-2021-000138,Natural,Biological,Epidemic,Viral disease,NaN,Meningitis,...,NaN,301.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14642,2021-0020-SRB,2021,20,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,22.0,NaN,NaN,NaN,NaN,1,25374;25378;25379;25380;25383;25386;25397,NaN,"Jablanicki, Kosovski, Kosovsko-mitrovatski, Ko..."
14643,2021-0481-SSD,2021,481,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,500000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.shape

(14644, 47)

In [11]:
df.columns

Index(['Dis No', 'Year', 'Seq', 'Glide', 'Disaster Group', 'Disaster Subgroup',
       'Disaster Type', 'Disaster Subtype', 'Disaster Subsubtype',
       'Event Name', 'Country', 'ISO', 'Region', 'Continent', 'Location',
       'Origin', 'Associated Dis', 'Associated Dis2', 'OFDA Response',
       'Appeal', 'Declaration', 'Aid Contribution', 'Dis Mag Value',
       'Dis Mag Scale', 'Latitude', 'Longitude', 'Local Time', 'River Basin',
       'Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month',
       'End Day', 'Total Deaths', 'No Injured', 'No Affected', 'No Homeless',
       'Total Affected', 'Reconstruction Costs ('000 US$)',
       'Insured Damages ('000 US$)', 'Total Damages ('000 US$)', 'CPI',
       'Adm Level', 'Admin1 Code', 'Admin2 Code', 'Geo Locations'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 47 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Dis No                           14644 non-null  str
 1   Year                             14644 non-null  int64
 2   Seq                              14644 non-null  int64
 3   Glide                            1581 non-null   str
 4   Disaster Group                   14644 non-null  str
 5   Disaster Subgroup                14644 non-null  str
 6   Disaster Type                    14644 non-null  str
 7   Disaster Subtype                 11897 non-null  str
 8   Disaster Subsubtype              1044 non-null   str
 9   Event Name                       3645 non-null   str
 10  Country                          14644 non-null  str
 11  ISO                              14644 non-null  str
 12  Region                           14644 non-null  str
 13  Continent                        14644 non-null  str
 14  Location                         13298 non-null  str
 15  Origin                           3780 non-null   str
 16  Associated Dis                   3232 non-null   str
 17  Associated Dis2                  698 non-null    str
 18  OFDA Response                    1450 non-null   str
 19  Appeal                           2440 non-null   str
 20  Declaration                      3127 non-null   str
 21  Aid Contribution                 677 non-null    float64
 22  Dis Mag Value                    4569 non-null   float64
 23  Dis Mag Scale                    13571 non-null  str
 24  Latitude                         2331 non-null   str
 25  Longitude                        2335 non-null   str
 26  Local Time                       765 non-null    str
 27  River Basin                      1285 non-null   str
 28  Start Year                       14644 non-null  int64
 29  Start Month                      14376 non-null  float64
 30  Start Day                        11577 non-null  float64
 31  End Year                         14644 non-null  int64
 32  End Month                        14095 non-null  float64
 33  End Day                          11650 non-null  float64
 34  Total Deaths                     10199 non-null  float64
 35  No Injured                       3651 non-null   float64
 36  No Affected                      8846 non-null   float64
 37  No Homeless                      2249 non-null   float64
 38  Total Affected                   11041 non-null  float64
 39  Reconstruction Costs ('000 US$)  31 non-null     float64
 40  Insured Damages ('000 US$)       1094 non-null   float64
 41  Total Damages ('000 US$)         4863 non-null   float64
 42  CPI                              14329 non-null  float64
 43  Adm Level                        7855 non-null   str
 44  Admin1 Code                      4581 non-null   str
 45  Admin2 Code                      3965 non-null   str
 46  Geo Locations                    7855 non-null   str
dtypes: float64(15), int64(4), str(28)
memory usage: 8.5 MB

In [13]:
df.describe()

,Year,Seq,Aid Contribution,Dis Mag Value,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No Injured,No Affected,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI
count,14644.000000,14644.000000,6.770000e+02,4.569000e+03,14644.000000,14376.000000,11577.000000,14644.000000,14095.000000,11650.000000,10199.000000,3.651000e+03,8.846000e+03,2.249000e+03,1.104100e+04,3.100000e+01,1.094000e+03,4.863000e+03,14329.000000
mean,2001.596422,731.604958,1.254136e+05,5.093532e+04,2001.606323,6.411241,15.207912,2001.655763,6.549273,15.792618,361.813119,2.486686e+03,8.889099e+05,7.229559e+04,7.277392e+05,2.392251e+06,7.999424e+05,7.746866e+05,68.762532
std,12.538572,1912.021531,2.997875e+06,3.211007e+05,12.535872,3.393997,8.964592,12.537387,3.351351,8.872079,6495.045853,3.402404e+04,8.680288e+06,5.271422e+05,7.851210e+06,5.229397e+06,3.060283e+06,4.901266e+06,21.429182
min,1970.000000,1.000000,1.000000e+00,-5.700000e+01,1970.000000,1.000000,1.000000,1970.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00,8.400000e+01,3.400000e+01,2.000000e+00,15.001282
25%,1993.000000,130.000000,1.750000e+02,7.000000e+00,1993.000000,4.000000,7.000000,1993.000000,4.000000,8.000000,5.000000,1.200000e+01,1.200000e+03,5.140000e+02,6.320000e+02,1.200000e+04,5.000000e+04,1.000000e+04,55.816107
50%,2003.000000,304.000000,7.210000e+02,1.800000e+02,2003.000000,7.000000,15.000000,2003.000000,7.000000,16.000000,16.000000,5.000000e+01,1.000000e+04,3.000000e+03,5.736000e+03,1.940000e+05,1.725000e+05,7.100000e+04,69.500473
75%,2012.000000,503.000000,3.511000e+03,1.515000e+04,2012.000000,9.000000,23.000000,2012.000000,9.000000,24.000000,50.000000,2.000000e+02,8.855250e+04,1.600000e+04,5.600000e+04,1.520376e+06,5.000000e+05,3.500000e+05,86.912465
max,2021.000000,9881.000000,7.800000e+07,1.302587e+07,2021.000000,12.000000,31.000000,2021.000000,12.000000,31.000000,300000.000000,1.800000e+06,3.300000e+08,1.585000e+07,3.300000e+08,2.500000e+07,6.000000e+07,2.100000e+08,100.000000

In [14]:
df.isnull().sum()

Dis No                                 0
Year                                   0
Seq                                    0
Glide                              13063
Disaster Group                         0
Disaster Subgroup                      0
Disaster Type                          0
Disaster Subtype                    2747
Disaster Subsubtype                13600
Event Name                         10999
Country                                0
ISO                                    0
Region                                 0
Continent                              0
Location                            1346
Origin                             10864
Associated Dis                     11412
Associated Dis2                    13946
OFDA Response                      13194
Appeal                             12204
Declaration                        11517
Aid Contribution                   13967
Dis Mag Value                      10075
Dis Mag Scale                       1073
Latitude                           12313
Longitude                          12309
Local Time                         13879
River Basin                        13359
Start Year                             0
Start Month                          268
Start Day                           3067
End Year                               0
End Month                            549
End Day                             2994
Total Deaths                        4445
No Injured                         10993
No Affected                         5798
No Homeless                        12395
Total Affected                      3603
Reconstruction Costs ('000 US$)    14613
Insured Damages ('000 US$)         13550
Total Damages ('000 US$)            9781
CPI                                  315
Adm Level                           6789
Admin1 Code                        10063
Admin2 Code                        10679
Geo Locations                       6789
dtype: int64

In [15]:
df.isnull().sum()[df.isnull().sum() > 0]

Glide                              13063
Disaster Subtype                    2747
Disaster Subsubtype                13600
Event Name                         10999
Location                            1346
Origin                             10864
Associated Dis                     11412
Associated Dis2                    13946
OFDA Response                      13194
Appeal                             12204
Declaration                        11517
Aid Contribution                   13967
Dis Mag Value                      10075
Dis Mag Scale                       1073
Latitude                           12313
Longitude                          12309
Local Time                         13879
River Basin                        13359
Start Month                          268
Start Day                           3067
End Month                            549
End Day                             2994
Total Deaths                        4445
No Injured                         10993
No Affected                         5798
No Homeless                        12395
Total Affected                      3603
Reconstruction Costs ('000 US$)    14613
Insured Damages ('000 US$)         13550
Total Damages ('000 US$)            9781
CPI                                  315
Adm Level                           6789
Admin1 Code                        10063
Admin2 Code                        10679
Geo Locations                       6789
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.sample(5)

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
4965,1997-0194-RUS,1997,194,NaN,Natural,Climatological,Wildfire,Forest fire,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,62.020757,NaN,NaN,NaN,NaN
5354,1998-9324-FJI,1998,9324,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,...,NaN,263455.0,NaN,NaN,NaN,62.983501,NaN,NaN,NaN,NaN
7214,2002-0837-COD,2002,837,NaN,Natural,Biological,Epidemic,Viral disease,NaN,Influenza,...,NaN,500000.0,NaN,NaN,NaN,69.500473,NaN,NaN,NaN,NaN
12947,2019-0315-GRC,2019,315,NaN,Natural,Meteorological,Storm,Convective storm,Tornado,NaN,...,NaN,123.0,NaN,NaN,NaN,98.781448,2,NaN,16697,Chalkidikis (Adm2).
9268,2008-0325-CHN,2008,325,NaN,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,...,13500.0,13529.0,NaN,NaN,NaN,83.189023,2,NaN,13261,Guangyuan (Adm2).

In [18]:
df.nunique()

Dis No                             14644
Year                                  52
Seq                                 1265
Glide                               1086
Disaster Group                         1
Disaster Subgroup                      6
Disaster Type                         14
Disaster Subtype                      27
Disaster Subsubtype                   12
Event Name                          1488
Country                              228
ISO                                  228
Region                                23
Continent                              5
Location                           11995
Origin                               660
Associated Dis                        30
Associated Dis2                       29
OFDA Response                          1
Appeal                                 2
Declaration                            2
Aid Contribution                     556
Dis Mag Value                       1860
Dis Mag Scale                          5
Latitude                            2091
Longitude                           2095
Local Time                           608
River Basin                         1213
Start Year                            52
Start Month                           12
Start Day                             31
End Year                              52
End Month                             12
End Day                               31
Total Deaths                         710
No Injured                           713
No Affected                         3492
No Homeless                          840
Total Affected                      4901
Reconstruction Costs ('000 US$)       29
Insured Damages ('000 US$)           362
Total Damages ('000 US$)            1519
CPI                                   51
Adm Level                              3
Admin1 Code                         3434
Admin2 Code                         3445
Geo Locations                       6354
dtype: int64

In [19]:
df.dtypes

Dis No                                 str
Year                                 int64
Seq                                  int64
Glide                                  str
Disaster Group                         str
Disaster Subgroup                      str
Disaster Type                          str
Disaster Subtype                       str
Disaster Subsubtype                    str
Event Name                             str
Country                                str
ISO                                    str
Region                                 str
Continent                              str
Location                               str
Origin                                 str
Associated Dis                         str
Associated Dis2                        str
OFDA Response                          str
Appeal                                 str
Declaration                            str
Aid Contribution                   float64
Dis Mag Value                      float64
Dis Mag Scale                          str
Latitude                               str
Longitude                              str
Local Time                             str
River Basin                            str
Start Year                           int64
Start Month                        float64
Start Day                          float64
End Year                             int64
End Month                          float64
End Day                            float64
Total Deaths                       float64
No Injured                         float64
No Affected                        float64
No Homeless                        float64
Total Affected                     float64
Reconstruction Costs ('000 US$)    float64
Insured Damages ('000 US$)         float64
Total Damages ('000 US$)           float64
CPI                                float64
Adm Level                              str
Admin1 Code                            str
Admin2 Code                            str
Geo Locations                          str
dtype: object

In [20]:
df.memory_usage(deep=True)

Index                                  132
Dis No                              307524
Year                                117152
Seq                                 117152
Glide                               141841
Disaster Group                      219660
Disaster Subgroup                   299881
Disaster Type                       219193
Disaster Subtype                    282061
Disaster Subsubtype                 133324
Event Name                          162534
Country                             288176
ISO                                 161084
Region                              325154
Continent                           201130
Location                           1118972
Origin                              176560
Associated Dis                      170656
Associated Dis2                     130045
OFDA Response                       123333
Appeal                              124063
Declaration                         126151
Aid Contribution                    117152
Dis Mag Value                       117152
Dis Mag Scale                       174296
Latitude                            132576
Longitude                           133267
Local Time                          122748
River Basin                         153253
Start Year                          117152
Start Month                         117152
Start Day                           117152
End Year                            117152
End Month                           117152
End Day                             117152
Total Deaths                        117152
No Injured                          117152
No Affected                         117152
No Homeless                         117152
Total Affected                      117152
Reconstruction Costs ('000 US$)     117152
Insured Damages ('000 US$)          117152
Total Damages ('000 US$)            117152
CPI                                 117152
Adm Level                           128220
Admin1 Code                         233680
Admin2 Code                         210275
Geo Locations                       642644
dtype: int64

In [22]:
important_cols = [
    'Year',
    'Disaster Type',
    'Country',
    'Region',
    'Continent',
    'Total Deaths',
    'No Injured',
    'No Affected',
    'Total Affected',
    "Total Damages ('000 US$)"
]

df_imp = df[important_cols]

df_imp.head()

,Year,Disaster Type,Country,Region,Continent,Total Deaths,No Injured,No Affected,Total Affected,Total Damages ('000 US$)
0,1970,Flood,Argentina,South America,Americas,36.0,NaN,NaN,NaN,25000.0
1,1970,Storm,Australia,Australia and New Zealand,Oceania,13.0,NaN,NaN,NaN,72475.0
2,1970,Flood,Benin,Western Africa,Africa,NaN,NaN,NaN,NaN,200.0
3,1970,Storm,Bangladesh,Southern Asia,Asia,300000.0,NaN,3648000.0,3648000.0,86400.0
4,1970,Storm,Bangladesh,Southern Asia,Asia,17.0,NaN,110.0,110.0,NaN

In [23]:
df_imp.shape

(14644, 10)